language: java
before_install:
  - mysql -u travis  -e 'CREATE DATABASE testadmin;'
  - mysql -u root -e "CREATE USER 'spideradmin'@'localhost' IDENTIFIED BY 'testsuite';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON testadmin.* TO 'spideradmin'@'localhost';"
  - cat src/test/resources/testadmin.sql | mysql -u testadmin -ptestsuite testadmin

